### ISSUE TITLE
Request support for Teensy 4.1

### ISSUE THREAD

**Issue by KeyLaager** [gregtomasch/USFSMAX_MMC_Module#4]
#error "Sorry, i2c_t3 only works on Teensy LC and 3.x.  Use Wire for Teensy 4.0, 4.1, MicroMod." when trying to compile for Teensy 4.1

**Comment by gregtomasch** [comment]
Yes, the error message is true on its face. I have a version of the test sketch for Teensy 4.x that uses the standard "Wire" library included in the Teensyduino core. However, this version of the "Wire" library only works with the USFSMAX if the bit clock is set at 100kHz. At the default value of 400kHz, the I2C bus hangs in a few seconds... Apparently there have been some issues with the "Stock" version of the Teensy "Wire" library for a long time; I think that's why a third party wrote the "i2c_t3" library for Teensy 3.x in the first place.

I should note that Teensy 4.x is the only MCU to date known to have this problem... So I conclude that it is an issue with the Teensy 4'x "Wire" library. I have been reluctant to post this version of the test sketch for this reason...

If you want to try it anyway, email me at "poirot@earthlink.net" and I will send you a ZIP archive.

**Comment by KeyLaager** [comment]
Greg, thank you so much for your response. I sent you an email from
***@***.*** If you don’t mind, I would like to take a look
at the zip.

Very Respectfully,

Joshua
